version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: agora-mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: agora_db
      MYSQL_USER: agoradbuser
      MYSQL_PASSWORD: agoradbpass
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - JAVA_OPTS=-Xms256m -Xmx512m
    volumes:
      - ./:/app
    restart: on-failure

volumes:
  mysql-data: