spring:
  datasource:
    url: jdbc:mysql://mysql:3306/agora_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: agoradbuser
    password: agoradbpass
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080

jwt:
  secret: "troque-por-uma-chave-muito-secreta-e-curta" # em produção usar vault/secret manager
  expiration: 3600000 # 1 hora em ms